version: 2.1

jobs:
  build:
    docker:      
      - image: mcr.microsoft.com/dotnet/core/sdk:3.0
    environment:
      TAG: 0.1
      DOCKER_IMAGE: payment-gateway
    steps:
      - run: echo $TAG.$CIRCLE_BUILD_NUM  
      - checkout
      - run:
          name: Run Tests
          command: dotnet test -c Release
      - run:
          name: Dotnet publish
          command: dotnet publish --no-build -c Release -o published
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="18.06.3-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - setup_remote_docker
      - run: 
          name: Build and Publish docker image
          command: |
            docker build -t $DOCKER_IMAGE .
            docker tag $DOCKER_IMAGE $DOCKER_USER/$DOCKER_IMAGE:$TAG.$CIRCLE_BUILD_NUM 
            echo $DOCKER_PWD | docker login -u $DOCKER_USER --password-stdin 
            docker push $DOCKER_USER/$DOCKER_IMAGE:$TAG.$CIRCLE_BUILD_NUM