version: 2.1

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.0 
    environment:
      #TAG: 0.1.${CIRCLE_BUILD_NUM} # does not work
      TAG: 0.1 # does not work
    steps:      
      - run: echo $TAG.${CIRCLE_BUILD_NUM}
      - checkout
      - run:
          name: Run Tests
          command: dotnet test -c Release
      - run:
          name: Dotnet publish
          command: dotnet publish --no-build -c Release -o published